### ISSUE TITLE
numpy issue on macOS with Python 3.9

### ISSUE THREAD

**Issue by kimwalisch** [kimwalisch/primesieve-python#45]
TravisCI does not properly build primesieve binary wheels with Python 3.9 on macOS:

```
ommand: /tmp/cibw_bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-req-build-84lyd5tv/setup.py'"'"'; __file__='"'"'/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-req-build-84lyd5tv/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-pip-egg-info-k36xgmbz
         cwd: /private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-req-build-84lyd5tv/
    Complete output (10 lines):
    init_dgelsd failed init
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/pip-req-build-84lyd5tv/setup.py", line 167, in <module>
        from numpy.distutils.ccompiler import CCompiler_compile
      File "/tmp/pypy3.6-v7.3.2-osx64/site-packages/numpy/__init__.py", line 286, in <module>
        raise RuntimeError(msg)
    RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
    RankWarning: Polyfit may be poorly conditioned
```

The problem is caused by numpy, see https://github.com/numpy/numpy/issues/15947. Basically numpy 1.19 is buggy on macOS. This thread also contains a few workarounds. However I am not really sure if we need to fix this issue, all tests pass successfully!?

**Comment by kimwalisch** [comment]
Luckily with my latest changes this book has vanished.
